// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface Carousel {
  carousel_items: CarouselItem[];
  cta_link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  cta_label: string;
  component: "carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface CarouselItem {
  quote: string;
  category: string;
  footer_text: string;
  cta_link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  cta_label: string;
  right_image_background?: StoryblokAsset;
  right_image?: StoryblokAsset;
  person_avatar?: StoryblokAsset;
  person_name: string;
  person_role: string;
  component: "carousel_item";
  _uid: string;
  [k: string]: unknown;
}

export interface CarouselSection {
  text_blocks: TextBlock[];
  carousel: Carousel[];
  component: "carousel_section";
  _uid: string;
  [k: string]: unknown;
}

export interface HomePage {
  body?: (TextCardsSection | CarouselSection)[];
  component: "home_page";
  _uid: string;
  [k: string]: unknown;
}

export interface TextBlock {
  headline: string;
  description: string;
  component: "text_block";
  _uid: string;
  [k: string]: unknown;
}

export interface TextCard {
  icon: StoryblokAsset;
  heading: string;
  description: string;
  component: "text_card";
  _uid: string;
  [k: string]: unknown;
}

export interface TextCardsSection {
  cards: TextCard[];
  component: "text_cards_section";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = HomePage;
