// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface HomePage {
  body?: TextCardsSection[];
  component: "home_page";
  _uid: string;
  [k: string]: unknown;
}

export interface TextCard {
  icon: StoryblokAsset;
  heading: string;
  description: string;
  component: "text_card";
  _uid: string;
  [k: string]: unknown;
}

export interface TextCardsSection {
  cards: TextCard[];
  component: "text_cards_section";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = HomePage;
